{{/**

  Copyright (C) 2024 Dremio

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

**/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "nessie.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nessie.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nessie.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .number }}
      targetPort: {{ .number }}
      protocol: TCP
    {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  {{- if ge (int $.Capabilities.KubeVersion.Minor) 31 }}
  trafficDistribution: {{ .Values.service.trafficDistribution }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nessie.fullname" . }}-mgmt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nessie.labels" . | nindent 4 }}
  {{- with .Values.managementService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "nessie.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.managementService.portName }}
      port: {{ .Values.managementService.portNumber }}
      targetPort: {{ .Values.managementService.portNumber }}
      protocol: TCP
  publishNotReadyAddresses: true
{{- range $i, $svc := .Values.extraServices }}
{{- if not $svc.nameSuffix }}
{{- fail (printf "extraServices[%d]: missing required nameSuffix" $i) }}
{{- else if eq $svc.nameSuffix "-mgmt" }}
{{- fail (printf "extraServices[%d]: invalid nameSuffix" $i) }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nessie.fullname" $ }}{{ $svc.nameSuffix }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "nessie.labels" $ | nindent 4 }}
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.type }}
  selector:
    {{- include "nessie.selectorLabels" $ | nindent 4 }}
  ports:
    {{- range $svc.ports }}
    - name: {{ .name }}
      port: {{ .number }}
      targetPort: {{ .number }}
      protocol: TCP
    {{- end }}
  {{- if $svc.sessionAffinity }}
  sessionAffinity: {{ $svc.sessionAffinity }}
  {{- end }}
  {{- if $svc.clusterIP }}
  clusterIP: {{ $svc.clusterIP }}
  {{- end }}
  {{- if and $svc.externalTrafficPolicy (or (eq $svc.type "LoadBalancer") (eq $svc.type "NodePort")) }}
  externalTrafficPolicy: {{ $svc.externalTrafficPolicy }}
  {{- end }}
  {{- if $svc.internalTrafficPolicy }}
  internalTrafficPolicy: {{ $svc.internalTrafficPolicy }}
  {{- end }}
  {{- if and (ge (int $.Capabilities.KubeVersion.Minor) 31) ($svc.trafficDistribution) }}
  trafficDistribution: {{ $svc.trafficDistribution }}
  {{- end }}
{{- end }}
