apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-web-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: airflow.local
    http:
      paths:
      - backend:
          service:
            name: airflow-api-server
            port:
              number: 8080
        path: /
        pathType: Prefix