
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dags
  hostPath:
    path: "/home/rocky/airflow/dags"

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: plugins-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plugins
  hostPath:
    path: "/home/rocky/airflow/plugins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: dags
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: plugins
