
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka
  hostPath:
    path: "/Users/li.xinlong1/Project/zeus/airflow-plugins/helm/value/kafka/client"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  storageClassName: kafka
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi