apiVersion: v1
kind: Secret
metadata:
  name: nessie-credentials
type: Opaque
data:
  password: bmVzc2llMTIz
  username: bmVzc2ll
  awsAccessKeyId: SEdNTzNBRkZVSkNFRVNVUUtEU04=
  awsSecretAccessKey: WUhPdlg0Mklsd0w1T0I1VVZIUmxyVzBaRXBXR2gxS2lrU3g2YXpERg==
